### ISSUE TITLE
Error on Android app, missing catalog resources

### ISSUE THREAD

**Issue by marianofino** [CiscoDevNet/flare#4]
Hello!

Great project! I have tested the flare server and played with it and the sample objects.

I am having an issue when testing the Trilateral app for Android phone. It throws me that it cannot find the following layouts and views:

```
Error:(994, 41) error: cannot find symbol variable fragment_list
Error:(996, 55) error: cannot find symbol variable catalogListView
Error:(1046, 41) error: cannot find symbol variable fragment_list_thing
Error:(1052, 64) error: cannot find symbol variable thing_icon
Error:(1053, 61) error: cannot find symbol variable thing_name
Error:(1054, 68) error: cannot find symbol variable thing_description
Error:(1055, 62) error: cannot find symbol variable thing_price
Error:(1056, 65) error: cannot find symbol variable thing_distance
```

I've checked the files and couldn't find them in the app/res folder. Probably the error is from this commit: 6b0b856afb474756d330a210d5492805145c1c13

I am not an expert on Android so probably I am wrong.. Any help is welcome :smile: 

Thanks!

**Comment by azamlerc** [comment]
Hi Mariano,

Thanks for your interest in developing apps with Flare! 

You're right, there were two missing files that I had forgotten to commit:

```
java/Trilateral/app/src/main/res/layout/fragment_list.xml
java/Trilateral/app/src/main/res/layout/fragment_list_thing
```

I have added these to the project so that should fix these errors. Please give it another try and let me know if you have any further problems! Thanks for helping us to test the app.

Cheers,
Andrew

**Comment by marianofino** [comment]
It solved it! Thanks!
